const $=id=>document.getElementById(id);const keys=['bedtime','wake','quality','wakeups','deep','rem','light','snore','talk','noise','pulse','breath','oxygen','caffeine','exercise','screen','stress','notes'];
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
$('themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.theme=document.body.classList.contains('light')?'light':'dark'};if(localStorage.theme==='light')document.body.classList.add('light');
function hoursBetween(b,w){let [bh,bm]=b.split(':').map(Number),[wh,wm]=w.split(':').map(Number);let start=bh*60+bm,end=wh*60+wm;if(end<=start)end+=1440;return +(Math.max(0,(end-start)/60).toFixed(1));}
function score(r){let h=hoursBetween(r.bedtime,r.wake);let s=50; s+=Math.min(30,Math.max(0,30-Math.abs(8-h)*8)); s+=Number(r.quality)*6; s-=Number(r.wakeups)*4; s-=Number(r.snore)/5; s-=r.screen?6:0; s-=r.stress?8:0; s+=r.exercise?4:0; return Math.max(0,Math.min(100,Math.round(s)));}
function get(){return JSON.parse(localStorage.sleepRecords||'[]')}function set(a){localStorage.sleepRecords=JSON.stringify(a)}
$('saveBtn').onclick=()=>{let r={date:new Date().toLocaleDateString('es-ES'),created:Date.now()};keys.forEach(k=>{let el=$(k);r[k]=el.type==='checkbox'?el.checked:el.value});r.hours=hoursBetween(r.bedtime,r.wake);r.score=score(r);let a=get();a.unshift(r);set(a);render();};
function render(){let a=get();$('totalDays').textContent=a.length;if(!a.length){$('history').innerHTML='<small>No hay registros todavía.</small>';$('todayScore').textContent='--';$('scoreText').textContent='Registra tu sueño de hoy';return}let avg=x=>Math.round(a.reduce((s,r)=>s+Number(r[x]||0),0)/a.length);$('avgHours').textContent=(a.reduce((s,r)=>s+Number(r.hours||0),0)/a.length).toFixed(1);$('avgScore').textContent=avg('score');$('todayScore').textContent=a[0].score;$('scoreText').textContent=`${a[0].hours} h · ${a[0].bedtime} → ${a[0].wake}`;$('history').innerHTML=a.map((r,i)=>`<div class="row"><strong>${r.date} · Score ${r.score}</strong><small>${r.hours} h · Profundo ${r.deep}h · REM ${r.rem}h · Ligero ${r.light}h<br>Ronquidos ${r.snore} min · Pulso ${r.pulse} · O₂ ${r.oxygen}%</small></div>`).join('')}
render();
